[package]
name = "json-to-yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
serde_json = "1"
serde_yaml = "0"

[[bin]]
name = "j2y"
path = "src/main.rs"
