[package]
name = "yaml-to-json"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
clap = { version = "3.1", features = ["derive"] }
color = { path = "../color" }
serde_json = "1"
serde_yaml = "0"

[[bin]]
name = "y2j"
path = "src/main.rs"
