[package]
name = "yaml-to-json"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde_json = "1"
serde_yaml = "0"

[[bin]]
name = "y2j"
path = "src/main.rs"
